seed_everything: 42
data:
  class_path: data_model.M1datamodel_aqc.DMTBaseDataModule
  init_args:
    data_path: /zangzelin/data
    pca_dim: 64
    batch_size: 60000
    num_workers: 0
    K: 200
    n_hop: 1
model:
  class_path: model.baseline_tri.DMTEVT_model
  init_args:
    method: _umap
    data_name: aqc
    num_input_dim: 3000
    n_components: 2
    p1: 1
    p2: 2
    p3: 0
    random_state: 42
trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  enable_checkpointing: false
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: baseline_umap_aqc
      project: DiffTree_rz
      save_dir: wandb
  callbacks:
  - class_path: callbacks.xc_plot_callback.VisualizationCallback
    init_args:
      output_dir: outputs/plots/baseline_umap_aqc
      every_n_epochs: 1
  - class_path: callbacks.xc_plot_heterogeneity.HeterogeneityPlotCallback
    init_args:
      output_dir: outputs/plots/baseline_umap_aqc/heterogeneity
      every_n_epochs: 1
      target_label: 1
  - class_path: callbacks.Eval_density.FidelityEvalCallback
    init_args:
      every_n_epochs: 1
      down_sample: 3000
      knn_k: 12
      density_k: 15
