program: main.py
method: grid
project: TopoBranch_latent_parameter_sensitivity
name: latent_parameter_sensitivity_gast10k_seed42_retry
parameters:
  config:
    values:
    - configs/encoder_bench/parameter_sensitivity_latent/runs/gast10k_k_40_seed42.yaml
command:
- ${env}
- ${interpreter}
- ${program}
- fit
- ${args}
