program: main.py
method: grid
project: CONSISTENCY_EVAL
name: exaggeration_emb_sweep_difftree_v3_mnist

parameters:
  config:
    values:
      - 'configs/best_setup.yaml'

  model.exaggeration_emb:
    values: [2, 4, 6, 8, 10, 12]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
