program: main.py
method: grid
project: CONSISTENCY_EVAL
name: baseline_sweep_tsne

parameters:
  config:
    values:
      # Size 2 (6 groups)
      - 'configs/baseline_sweep/tsne/s2_0_6.yaml'
      - 'configs/baseline_sweep/tsne/s2_1_7.yaml'
      - 'configs/baseline_sweep/tsne/s2_2_7.yaml'
      - 'configs/baseline_sweep/tsne/s2_3_8.yaml'
      - 'configs/baseline_sweep/tsne/s2_4_9.yaml'
      - 'configs/baseline_sweep/tsne/s2_5_6.yaml'
      # Size 3 (6 groups)
      - 'configs/baseline_sweep/tsne/s3_0_6_9.yaml'
      - 'configs/baseline_sweep/tsne/s3_1_4_7.yaml'
      - 'configs/baseline_sweep/tsne/s3_1_5_6.yaml'
      - 'configs/baseline_sweep/tsne/s3_2_3_8.yaml'
      - 'configs/baseline_sweep/tsne/s3_3_5_8.yaml'
      - 'configs/baseline_sweep/tsne/s3_4_7_9.yaml'
      # Size 4 (4 groups)
      - 'configs/baseline_sweep/tsne/s4_0_1_4_7.yaml'
      - 'configs/baseline_sweep/tsne/s4_0_2_6_9.yaml'
      - 'configs/baseline_sweep/tsne/s4_2_3_5_8.yaml'
      - 'configs/baseline_sweep/tsne/s4_3_4_8_9.yaml'
      # Size 5 (3 groups)
      - 'configs/baseline_sweep/tsne/s5_01357.yaml'
      - 'configs/baseline_sweep/tsne/s5_13489.yaml'
      - 'configs/baseline_sweep/tsne/s5_24689.yaml'
      # Size 6 (1 groups)
      - 'configs/baseline_sweep/tsne/s6_023589.yaml'
      # Size 7 (2 groups)
      - 'configs/baseline_sweep/tsne/s7_0134579.yaml'
      - 'configs/baseline_sweep/tsne/s7_0235689.yaml'
      # Size 8 (1 groups)
      - 'configs/baseline_sweep/tsne/s8_01234689.yaml'
      # Size 10 (1 groups)
      - 'configs/baseline_sweep/tsne/s10_all.yaml'

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
