program: main.py
method: grid
project: CONSISTENCY_EVAL
name: epoch_sweep_difftree_v3_mnist

parameters:
  config:
    values:
      - 'configs/label_scaling_v3/diff_s2_1_7.yaml'
  data.batch_size:
    values: [6500]

  trainer.max_epochs:
    values: [200, 500, 1000, 1500, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 10000]

  trainer.check_val_every_n_epoch:
    value: 100

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
