"""Generate strict leave-one-out ablation configs for seeds 42, 43, and 44."""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
SOURCE_DIR = ROOT / "configs/encoder_bench/ablation_mechanism_latent_v2/runs"
RUN_DIR = HERE / "runs"
SOURCE_SEED = 42
SEEDS = (42, 43, 44)
EPOCHS = 1000
RUN_DATE = "20260811"
PROJECT = "TopoBranch_single_factor_loo_3seed_1000"
DATASETS = ("hcl", "epi", "mnist")
VARIANTS = (
    "full",
    "r1_distance",
    "r2_unidirectional",
    "r3_allpair",
    "r4_single_density",
    "r5_no_density",
)


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def one_callback(callbacks: list[dict], suffix: str) -> dict:
    matches = [item for item in callbacks if item["class_path"].endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"Expected one {suffix}, found {len(matches)}")
    return matches[0]


def build(dataset: str, variant: str, seed: int) -> tuple[str, dict]:
    source = (
        SOURCE_DIR
        / f"ablation_v2_latent-bn_{dataset}_{variant}_seed{SOURCE_SEED}.yaml"
    )
    cfg = copy.deepcopy(load(source))

    if cfg["seed_everything"] != SOURCE_SEED:
        raise ValueError(f"Unexpected source seed in {source}")
    if cfg["trainer"]["max_epochs"] != EPOCHS:
        raise ValueError(f"Unexpected trainer epochs in {source}")
    if cfg["model"]["init_args"]["max_epochs"] != EPOCHS:
        raise ValueError(f"Unexpected model epochs in {source}")

    cfg["seed_everything"] = seed
    run_name = (
        f"singlefactor_loo3seed1000_{dataset}_{variant}_"
        f"seed{seed}_c89_{RUN_DATE}"
    )
    out_root = (
        f"outputs/ablation/single_factor_loo_3seed_1000_{RUN_DATE}/"
        f"{dataset}/{variant}/seed{seed}"
    )

    logger = cfg["trainer"]["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "project": PROJECT,
            "save_dir": f"wandb/single_factor_loo_3seed_1000_{RUN_DATE}",
            "group": f"{dataset}_seed{seed}",
            "tags": [
                "strict-single-factor",
                "leave-one-out",
                "three-seed",
                "1000-epoch",
                "c89",
                RUN_DATE,
                dataset,
                variant,
                f"seed{seed}",
            ],
        }
    )

    callbacks = cfg["trainer"]["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {
            "dirpath": f"{out_root}/checkpoints",
            "filename": f"{run_name}-{{epoch:04d}}",
        }
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = (
        f"results/ablation/single_factor_loo_3seed_1000_{RUN_DATE}/"
        f"{run_name}/runtime.csv"
    )
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {
            "output_dir": f"{out_root}/figure",
            "method_name": f"latent-bn-{variant}-loo3seed1000",
        }
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")["init_args"].update(
        {
            "dataset_name": f"{dataset}_{variant}_loo3seed1000_seed{seed}",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": f"latent-bn-{variant}-loo3seed1000",
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()

    for dataset in DATASETS:
        for seed in SEEDS:
            for variant in VARIANTS:
                run_name, cfg = build(dataset, variant, seed)
                path = RUN_DIR / f"{run_name}.yaml"
                if variant == "full":
                    description = "Matched full control"
                else:
                    description = "Strict leave-one-out"
                header = (
                    "# Generated by configs/encoder_bench/"
                    "ablation_single_factor_loo_3seed_1000/generate_configs.py\n"
                    f"# {description}: {dataset}, {variant}, seed {seed}, "
                    f"{EPOCHS} epochs.\n"
                    "# Scientific settings match v2; only the requested seed and run identity differ.\n"
                )
                with path.open("w", encoding="utf-8") as handle:
                    handle.write(header)
                    yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)

    count = len(DATASETS) * len(SEEDS) * len(VARIANTS)
    print(f"Wrote {count} configs to {RUN_DIR}")


if __name__ == "__main__":
    main()
