"""Generate seed-42 latent-bn reruns with the accepted E18 paper renderer."""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
RUN_DIR = HERE / "runs"
SWEEP_DIR = HERE / "sweep"

# Longest-first so the ninth queued run is one of the short datasets.
DATASETS = (
    "emnist",
    "epi",
    "hcl",
    "tree",
    "mca",
    "mnist",
    "ng20",
    "gast10k",
    "act",
)


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def one_callback(callbacks: list[dict], suffix: str) -> dict:
    matches = [item for item in callbacks if item["class_path"].endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"Expected one {suffix}, found {len(matches)}")
    return matches[0]


def build(dataset: str) -> tuple[str, dict]:
    source = ROOT / (
        f"configs/encoder_bench/sweep_e18/runs/{dataset}_latent_bn_seed42.yaml"
    )
    cfg = copy.deepcopy(load(source))
    run_name = f"paper_exact_latent-bn_{dataset}_seed42"
    out_root = (
        f"outputs/paper_general_exact_rerun/latent_bn/{dataset}/seed42"
    )

    # c89 does not mount the historical /zangzelin/data alias.  Point to the
    # same shared files through their stable absolute storage path.
    if cfg["data"]["init_args"].get("data_path") == "/zangzelin/data":
        cfg["data"]["init_args"]["data_path"] = "/usr/storage/ruizhe/zangzelin/data"

    logger = cfg["trainer"]["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "project": "TopoBranch_encoder_paper_figures",
            "group": "exact_e18_paper_callback_rerun_seed42_v3",
            "save_dir": "wandb/paper_general_exact_rerun",
        }
    )

    callbacks = cfg["trainer"]["callbacks"]
    checkpoint = one_callback(callbacks, "ModelCheckpoint")
    checkpoint["init_args"].update(
        {
            "dirpath": f"{out_root}/checkpoints",
            "filename": f"{run_name}-{{epoch:04d}}",
            "save_last": True,
            "save_top_k": 0,
        }
    )
    diagnostic = one_callback(callbacks, "xc_plot_callback.VisualizationCallback")
    diagnostic["init_args"].update(
        {
            "output_dir": f"{out_root}/diagnostics",
            "save_embeddings": True,
            "embedding_method_name": "latent-bn",
        }
    )
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/paper_general_exact_rerun/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"

    paper = one_callback(callbacks, "PaperEmbeddingCallback")
    # Use the exact callback and visual parameters from the accepted E18
    # figures. W&B receives the PNG saved by this callback; upload does not
    # recreate or modify the Matplotlib figure.
    paper["class_path"] = (
        "callbacks.xc_paper_embedding_callback.PaperEmbeddingCallback"
    )
    paper["init_args"] = {
        "output_dir": f"{out_root}/paper",
        "method_name": "latent-bn",
        "color_key": "final_annotation",
        "every_n_epochs": None,
        "point_size": 1.5,
        "alpha": 0.5,
        "cmap": "tab20",
        "overflow_cmap": "gist_ncar",
        "figsize": 4.0,
        "dpi": 300,
        "formats": ["png"],
        "log_to_wandb": True,
        "wandb_key": "paper_embedding/figure",
    }

    callbacks.append(
        {
            "class_path": (
                "callbacks.xc_save_consolidated_embeddings."
                "SaveConsolidatedEmbeddingsCallback"
            ),
            "init_args": {
                "dataset_name": f"{dataset}_seed42",
                "output_dir": f"{out_root}/final_embedding",
                "save_format": "both",
                "embedding_method_name": "latent-bn",
            },
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    SWEEP_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()

    run_paths = []
    for dataset in DATASETS:
        run_name, cfg = build(dataset)
        path = RUN_DIR / f"{run_name}.yaml"
        header = (
            "# Generated by configs/encoder_bench/paper_general_seed42/generate_configs.py\n"
            f"# Exact E18 paper-callback rerun: {dataset}, latent-bn, seed 42.\n"
            "# Data, objective, projection head and optimizer match the E18 run exactly.\n"
        )
        with path.open("w", encoding="utf-8") as handle:
            handle.write(header)
            yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
        run_paths.append(path.relative_to(ROOT).as_posix())

    sweep = {
        "program": "main.py",
        "method": "grid",
        "project": "TopoBranch_encoder_paper_figures",
        "name": "latent_bn_general_exact_e18_paper_callback_rerun_seed42_v3",
        "parameters": {"config": {"values": run_paths}},
        "command": ["${env}", "${interpreter}", "${program}", "fit", "${args}"],
    }
    sweep_path = SWEEP_DIR / "exact_e18_paper_callback_rerun_v3.yaml"
    with sweep_path.open("w", encoding="utf-8") as handle:
        handle.write(
            "# Nine general datasets using the exact accepted E18 paper callback; "
            "latent-bn, seed 42; longest-first.\n"
        )
        yaml.safe_dump(sweep, handle, sort_keys=False, allow_unicode=True)
    print(f"Wrote {len(run_paths)} run configs and {sweep_path}")


if __name__ == "__main__":
    main()
