program: main.py
method: grid
project: DiffTree_rz
name: sweep_density_weight
parameters:
  config:
    values:
      - 'configs/density_weight_sweep/temp/difftree_density_mnist.yaml'
  model.density_weight:
    values: [2e-5, 5e-5, 8e-5, 1e-4, 3e-4, 5e-4, 8e-4, 1e-3, 3e-3, 5e-3, 8e-3, 1e-2, 3e-2, 5e-2, 8e-2]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
