"""Generate the five ACT latent-bn reruns with batch size 4096.

The source of truth is the E18 ACT latent-bn configuration for each seed.  The
scientific configuration is preserved except for the requested batch size.
Run names and artifact paths are isolated so the original batch-5000 results
cannot be overwritten or confused with this correction experiment.
"""

from copy import deepcopy
from pathlib import Path

import yaml


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
SOURCE_DIR = REPO_ROOT / "configs" / "encoder_bench" / "sweep_e18" / "runs"
RUNS_DIR = HERE / "runs"
SEEDS = (42, 43, 44, 45, 46)
PROJECT = "TopoBranch_ACT_bs4096_5seed_1000"
DATE_TAG = "20260814"


def build(seed: int) -> tuple[str, dict]:
    source = SOURCE_DIR / f"act_latent_bn_seed{seed}.yaml"
    config = yaml.safe_load(source.read_text(encoding="utf-8"))
    config = deepcopy(config)

    run_name = f"act_latent_bn_bs4096_seed{seed}_c90_{DATE_TAG}"
    output_root = f"outputs/encoder_tuning/ACT_bs4096_5seed_1000/{run_name}"
    config["data"]["init_args"]["batch_size"] = 4096

    logger_args = config["trainer"]["logger"]["init_args"]
    logger_args["name"] = run_name
    logger_args["project"] = PROJECT

    for callback in config["trainer"]["callbacks"]:
        callback_path = callback["class_path"]
        init_args = callback.setdefault("init_args", {})
        if callback_path.endswith("ModelCheckpoint"):
            init_args["dirpath"] = f"{output_root}/checkpoints"
            init_args["filename"] = run_name + "-{epoch:04d}"
        elif callback_path.endswith("VisualizationCallback"):
            init_args["output_dir"] = f"{output_root}/plots"
        elif callback_path.endswith("HeterogeneityPlotCallback"):
            init_args["output_dir"] = f"{output_root}/heterogeneity"
        elif callback_path.endswith("RuntimeProfilerCallback"):
            init_args["output_path"] = f"results/encoder_tuning/ACT_bs4096_5seed_1000/{run_name}/runtime.csv"
        elif callback_path.endswith("PaperEmbeddingCallback"):
            init_args["output_dir"] = f"{output_root}/paper"
            init_args["log_to_wandb"] = True
            init_args["wandb_key"] = "paper_embedding/final_annotation"
        elif callback_path.endswith("RuntimeInfoCallback"):
            init_args["output_dir"] = f"{output_root}/runtime_info"

    return run_name, config


def main() -> None:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    for seed in SEEDS:
        run_name, config = build(seed)
        header = (
            "# Generated by configs/encoder_bench/act_bs4096_5seed_1000/generate_configs.py\n"
            f"# ACT latent-bn correction run, seed {seed}: E18 config with batch size 4096.\n"
            "# PaperEmbeddingCallback saves and uploads the final paper-ready 2D plot.\n"
        )
        destination = RUNS_DIR / f"{run_name}.yaml"
        destination.write_text(
            header + yaml.safe_dump(config, sort_keys=False, default_flow_style=False),
            encoding="utf-8",
        )
        print(destination.relative_to(REPO_ROOT))


if __name__ == "__main__":
    main()
