program: main.py
method: grid
project: DiffTree_rz
name: baseline_dataset_5seed_sweep

parameters:
  config:
    values:
      - 'configs/dmtme_dataset_baselines/densmap/act.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/epi.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/mca.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/densmap/tree.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/act.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/epi.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/mca.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/denssne/tree.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/act.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/epi.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/mca.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/pacmap/tree.yaml'
      - 'configs/dmtme_dataset_baselines/phate/act.yaml'
      - 'configs/dmtme_dataset_baselines/phate/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/phate/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/phate/epi.yaml'
      - 'configs/dmtme_dataset_baselines/phate/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/phate/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/phate/mca.yaml'
      - 'configs/dmtme_dataset_baselines/phate/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/phate/tree.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/act.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/epi.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/mca.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/tsne/tree.yaml'
      - 'configs/dmtme_dataset_baselines/umap/act.yaml'
      - 'configs/dmtme_dataset_baselines/umap/aqc.yaml'
      - 'configs/dmtme_dataset_baselines/umap/emnist.yaml'
      - 'configs/dmtme_dataset_baselines/umap/epi.yaml'
      - 'configs/dmtme_dataset_baselines/umap/gast10k.yaml'
      - 'configs/dmtme_dataset_baselines/umap/hcl.yaml'
      - 'configs/dmtme_dataset_baselines/umap/mca.yaml'
      - 'configs/dmtme_dataset_baselines/umap/ng20.yaml'
      - 'configs/dmtme_dataset_baselines/umap/tree.yaml'

  seed_everything:
    values: [42, 43, 44, 45, 46]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
