"""Generate the seven seed-42 causal checks requested by the advisor.

Every scientific setting is copied from the corresponding completed v2
ablation config.  The generated runs change only numerical implementation,
logging/fail-fast behaviour, and run/output identity:

* differentiable global (shared-axis) embedding standardization;
* a 1e-4 kNN-distance and Pearson-denominator floor;
* manifold and density losses consume the same normalized embedding;
* every-step collapse diagnostics and immediate non-finite termination.
"""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
RUN_DIR = HERE / "runs"
SWEEP_DIR = HERE / "sweep"
PROJECT = "TopoBranch_global_standardization_diagnostic"
SEED = 42
TARGETS = {
    "epi": ("full", "base", "b2_bidirectional", "b5_multi_density"),
    "hcl": ("full", "b4_single_density"),
    "mnist": ("full",),
}


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def one_callback(callbacks: list[dict], suffix: str) -> dict:
    matches = [item for item in callbacks if item["class_path"].endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"Expected one {suffix}, found {len(matches)}")
    return matches[0]


def source_config(dataset: str, variant: str) -> Path:
    return (
        ROOT
        / "configs/encoder_bench/ablation_mechanism_latent_v2/runs"
        / f"ablation_v2_latent-bn_{dataset}_{variant}_seed42.yaml"
    )


def build(dataset: str, variant: str) -> tuple[str, dict]:
    cfg = copy.deepcopy(load(source_config(dataset, variant)))
    run_name = f"globalstd_latent-bn_{dataset}_{variant}_seed{SEED}"
    out_root = f"outputs/ablation/global_standardization/{dataset}/{variant}/seed{SEED}"

    cfg["seed_everything"] = SEED
    model_args = cfg["model"]["init_args"]
    model_args.update(
        {
            "embedding_standardization": "differentiable_global",
            "embedding_std_floor": 1.0e-4,
            "density_distance_floor": 1.0e-4,
            "density_pearson_floor": 1.0e-4,
        }
    )

    trainer = cfg["trainer"]
    trainer["log_every_n_steps"] = 1
    logger = trainer["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "project": PROJECT,
            "save_dir": "wandb/global_standardization_diagnostic",
            "tags": [
                "global-standardization-diagnostic",
                "differentiable-global",
                "density-floor-1e-4",
                "fail-fast",
                dataset,
                variant,
                f"seed{SEED}",
            ],
        }
    )

    callbacks = trainer["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {"dirpath": f"{out_root}/checkpoints", "filename": f"{run_name}-{{epoch:04d}}"}
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/global_standardization/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"
    one_callback(callbacks, "EncoderBenchmarkCallback")["init_args"].update(
        {"check_grad_every_n_steps": 1, "fail_on_nonfinite": True}
    )

    method_name = f"latent-bn-{variant}-globalstd"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {"output_dir": f"{out_root}/figure", "method_name": method_name}
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")["init_args"].update(
        {
            "dataset_name": f"{dataset}_{variant}_globalstd_seed{SEED}",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": method_name,
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    SWEEP_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()
    for stale in SWEEP_DIR.glob("*.yaml"):
        stale.unlink()

    run_paths = []
    for dataset, variants in TARGETS.items():
        for variant in variants:
            run_name, cfg = build(dataset, variant)
            path = RUN_DIR / f"{run_name}.yaml"
            header = (
                "# Generated by ablation_global_standardization_diagnostic/generate_configs.py\n"
                f"# dataset={dataset}; variant={variant}; seed={SEED}\n"
                "# Only numerical implementation, diagnostics, and output identity differ from v2.\n"
            )
            with path.open("w", encoding="utf-8") as handle:
                handle.write(header)
                yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
            run_paths.append(path)

    sweep = {
        "program": "main.py",
        "method": "grid",
        "project": PROJECT,
        "name": "global_standardization_density_guard_seed42_c89",
        "parameters": {
            "config": {
                "values": [path.relative_to(ROOT).as_posix() for path in run_paths]
            }
        },
        "command": ["${env}", "${interpreter}", "${program}", "fit", "${args}"],
    }
    sweep_path = SWEEP_DIR / "sweep_global_standardization_seed42_c89.yaml"
    with sweep_path.open("w", encoding="utf-8") as handle:
        handle.write("# Seven-run advisor-requested numerical diagnostic on c89.\n")
        yaml.safe_dump(sweep, handle, sort_keys=False, allow_unicode=True)
    print(f"Wrote {len(run_paths)} configs and {sweep_path}")


if __name__ == "__main__":
    main()
