"""Generate the seven-run pilot after correcting AMP overflow handling."""

from __future__ import annotations

from pathlib import Path

import yaml

from generate_configs import ROOT, SEED, TARGETS, build, one_callback


REVISION = "globalscalerfix"
HERE = Path(__file__).resolve().parent
RUN_DIR = HERE / "runs_scalerfix"


def revise(dataset: str, variant: str) -> tuple[str, dict]:
    _, cfg = build(dataset, variant)
    run_name = f"{REVISION}_latent-bn_{dataset}_{variant}_seed{SEED}"
    artifact_root = (
        f"outputs/ablation/global_standardization_scalerfix/"
        f"{dataset}/{variant}/seed{SEED}"
    )
    trainer = cfg["trainer"]
    trainer["logger"]["init_args"].update(
        {
            "name": run_name,
            "save_dir": "wandb/global_standardization_scalerfix",
            "tags": [
                "global-standardization-scalerfix-pilot",
                "recoverable-amp-overflow",
                "near-line-threshold-0.05",
                dataset,
                variant,
                f"seed{SEED}",
            ],
        }
    )
    callbacks = trainer["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {
            "dirpath": f"{artifact_root}/checkpoints",
            "filename": f"{run_name}-{{epoch:04d}}",
        }
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{artifact_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{artifact_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/global_standardization_scalerfix/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{artifact_root}/runtime_info"
    method_name = f"latent-bn-{variant}-{REVISION}"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {"output_dir": f"{artifact_root}/figure", "method_name": method_name}
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")[
        "init_args"
    ].update(
        {
            "dataset_name": f"{dataset}_{variant}_{REVISION}_seed{SEED}",
            "output_dir": f"{artifact_root}/final_embedding",
            "embedding_method_name": method_name,
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()
    paths = []
    for dataset, variants in TARGETS.items():
        for variant in variants:
            run_name, cfg = revise(dataset, variant)
            path = RUN_DIR / f"{run_name}.yaml"
            with path.open("w", encoding="utf-8") as handle:
                handle.write(
                    "# Generated by generate_scalerfix_pilot_configs.py\n"
                    f"# dataset={dataset}; variant={variant}; seed={SEED}\n"
                )
                yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
            paths.append(path)
    if len(paths) != 7:
        raise RuntimeError(f"Expected seven pilot configs, wrote {len(paths)}")
    print(f"Wrote {len(paths)} scaler-fix pilot configs under {RUN_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
