"""Generate the EPI-b2 AMP versus FP32 numerical-causality canaries."""

from __future__ import annotations

from pathlib import Path

import yaml

from generate_configs import HERE, ROOT, one_callback
from generate_postfix_configs import revise_identity


RUN_DIR = HERE / "runs_causal_precision"
SCENARIOS = {
    "amp16": {
        "precision": "16-mixed",
        "max_epochs": 25,
        "fail_on_nonfinite": True,
        "trace_leaf_modules": True,
    },
    "fp32": {
        "precision": "32-true",
        "max_epochs": 25,
        "fail_on_nonfinite": True,
        "trace_leaf_modules": True,
    },
    # GradScaler deliberately exposes Inf gradients after unscaling so that it
    # can skip the optimizer step and reduce its scale.  This arm determines
    # whether fail-fast has been aborting that normal recovery path.
    "amp16_scaler_tolerant": {
        "precision": "16-mixed",
        "max_epochs": 25,
        "fail_on_nonfinite": False,
        "trace_leaf_modules": False,
    },
    "amp16_fixed_full": {
        "precision": "16-mixed",
        "max_epochs": 1000,
        "fail_on_nonfinite": True,
        "trace_leaf_modules": False,
    },
}


def build(label: str, scenario: dict) -> tuple[str, dict]:
    _, cfg = revise_identity("epi", "b2_bidirectional")
    run_name = f"causal_{label}_latent-bn_epi_b2_bidirectional_seed42"
    out_root = f"outputs/ablation/global_standardization_causal/{label}/epi_b2_seed42"
    trainer = cfg["trainer"]
    trainer.update(
        {"max_epochs": scenario["max_epochs"], "precision": scenario["precision"]}
    )
    trainer["logger"]["init_args"].update(
        {
            "name": run_name,
            "save_dir": f"wandb/global_standardization_causal/{label}",
            "tags": [
                "global-standardization-causal",
                "epi-b2-canary",
                label,
                "seed42",
            ],
        }
    )
    one_callback(trainer["callbacks"], "ModelCheckpoint")["init_args"].update(
        {"dirpath": f"{out_root}/checkpoints", "filename": f"{run_name}-{{epoch:04d}}"}
    )
    one_callback(trainer["callbacks"], "xc_plot_callback.VisualizationCallback")[
        "init_args"
    ]["output_dir"] = f"{out_root}/diagnostics"
    one_callback(trainer["callbacks"], "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(trainer["callbacks"], "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/global_standardization_causal/{label}/runtime.csv"
    one_callback(trainer["callbacks"], "PaperEmbeddingCallback")["init_args"].update(
        {"output_dir": f"{out_root}/figure", "method_name": f"latent-bn-b2-{label}"}
    )
    one_callback(trainer["callbacks"], "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"
    one_callback(trainer["callbacks"], "SaveConsolidatedEmbeddingsCallback")[
        "init_args"
    ].update(
        {
            "dataset_name": f"epi_b2_causal_{label}_seed42",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": f"latent-bn-b2-{label}",
        }
    )
    trainer["callbacks"].insert(
        0,
        {
            "class_path": "callbacks.numerical_causality.NumericalCausalityCallback",
            "init_args": {
                "output_path": f"results/ablation/global_standardization_causal/{label}/trace.jsonl",
                "trace_leaf_modules": scenario["trace_leaf_modules"],
            },
        },
    )
    one_callback(trainer["callbacks"], "EncoderBenchmarkCallback")["init_args"][
        "fail_on_nonfinite"
    ] = scenario["fail_on_nonfinite"]
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()
    paths = []
    for label, scenario in SCENARIOS.items():
        run_name, cfg = build(label, scenario)
        path = RUN_DIR / f"{run_name}.yaml"
        with path.open("w", encoding="utf-8") as handle:
            handle.write(
                "# Generated by generate_causal_precision_configs.py\n"
                f"# precision={scenario['precision']}; scenario={label}.\n"
            )
            yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
        paths.append(path)
    print(f"Wrote {len(paths)} causal configs under {RUN_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
