"""Generate isolated rerun configs for the numerical-backward fix.

Scientific settings come from the seven validated global-standardization
diagnostics. Only run identity and artifact destinations change, so the rerun
cannot overwrite checkpoints, plots, or embeddings from the first diagnostic.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from generate_configs import HERE, ROOT, SEED, TARGETS, build, one_callback


REVISION = "globalstdfix"
RUN_DIR = HERE / "runs_postfix"


def revise_identity(dataset: str, variant: str) -> tuple[str, dict]:
    _, cfg = build(dataset, variant)
    run_name = f"{REVISION}_latent-bn_{dataset}_{variant}_seed{SEED}"
    out_root = (
        f"outputs/ablation/global_standardization_postfix/"
        f"{dataset}/{variant}/seed{SEED}"
    )

    trainer = cfg["trainer"]
    logger = trainer["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "save_dir": "wandb/global_standardization_postfix",
            "tags": list(logger.get("tags", []))
            + ["sqrt-floor-before-root", "skip-zero-weight-density"],
        }
    )

    callbacks = trainer["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {"dirpath": f"{out_root}/checkpoints", "filename": f"{run_name}-{{epoch:04d}}"}
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/global_standardization_postfix/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"

    method_name = f"latent-bn-{variant}-{REVISION}"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {"output_dir": f"{out_root}/figure", "method_name": method_name}
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")["init_args"].update(
        {
            "dataset_name": f"{dataset}_{variant}_{REVISION}_seed{SEED}",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": method_name,
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()

    run_paths: list[Path] = []
    for dataset, variants in TARGETS.items():
        for variant in variants:
            run_name, cfg = revise_identity(dataset, variant)
            path = RUN_DIR / f"{run_name}.yaml"
            header = (
                "# Generated by generate_postfix_configs.py\n"
                f"# dataset={dataset}; variant={variant}; seed={SEED}\n"
                "# Scientific settings match the validated global-standardization run.\n"
            )
            with path.open("w", encoding="utf-8") as handle:
                handle.write(header)
                yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
            run_paths.append(path)

    print(f"Wrote {len(run_paths)} post-fix configs under {RUN_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
