program: main.py
method: grid
project: DiffTree_rz
name: baseline_plotting

parameters:
  config:
    values:
      - 'configs/plotting/baseline/densmap/act.yaml'
      # - 'configs/plotting/baseline/densmap/aqc.yaml'
      - 'configs/plotting/baseline/densmap/emnist.yaml'
      - 'configs/plotting/baseline/densmap/epi.yaml'
      - 'configs/plotting/baseline/densmap/gast10k.yaml'
      - 'configs/plotting/baseline/densmap/hcl.yaml'
      - 'configs/plotting/baseline/densmap/mca.yaml'
      - 'configs/plotting/baseline/densmap/mnist.yaml'
      - 'configs/plotting/baseline/densmap/ng20.yaml'
      - 'configs/plotting/baseline/densmap/tree.yaml'
      - 'configs/plotting/baseline/densne/act.yaml'
      # - 'configs/plotting/baseline/densne/aqc.yaml'
      # - 'configs/plotting/baseline/densne/emnist.yaml'
      - 'configs/plotting/baseline/densne/epi.yaml'
      - 'configs/plotting/baseline/densne/gast10k.yaml'
      - 'configs/plotting/baseline/densne/hcl.yaml'
      - 'configs/plotting/baseline/densne/mca.yaml'
      - 'configs/plotting/baseline/densne/mnist.yaml'
      - 'configs/plotting/baseline/densne/ng20.yaml'
      - 'configs/plotting/baseline/densne/tree.yaml'
      - 'configs/plotting/baseline/pacmap/act.yaml'
      # - 'configs/plotting/baseline/pacmap/aqc.yaml'
      - 'configs/plotting/baseline/pacmap/emnist.yaml'
      - 'configs/plotting/baseline/pacmap/epi.yaml'
      - 'configs/plotting/baseline/pacmap/gast10k.yaml'
      - 'configs/plotting/baseline/pacmap/hcl.yaml'
      - 'configs/plotting/baseline/pacmap/mca.yaml'
      - 'configs/plotting/baseline/pacmap/mnist.yaml'
      - 'configs/plotting/baseline/pacmap/ng20.yaml'
      - 'configs/plotting/baseline/pacmap/tree.yaml'
      - 'configs/plotting/baseline/phate/act.yaml'
      # - 'configs/plotting/baseline/phate/aqc.yaml'
      - 'configs/plotting/baseline/phate/emnist.yaml'
      - 'configs/plotting/baseline/phate/epi.yaml'
      - 'configs/plotting/baseline/phate/gast10k.yaml'
      - 'configs/plotting/baseline/phate/hcl.yaml'
      - 'configs/plotting/baseline/phate/mca.yaml'
      - 'configs/plotting/baseline/phate/mnist.yaml'
      - 'configs/plotting/baseline/phate/ng20.yaml'
      - 'configs/plotting/baseline/phate/tree.yaml'
      - 'configs/plotting/baseline/tsne/act.yaml'
      # - 'configs/plotting/baseline/tsne/aqc.yaml'
      - 'configs/plotting/baseline/tsne/emnist.yaml'
      - 'configs/plotting/baseline/tsne/epi.yaml'
      - 'configs/plotting/baseline/tsne/gast10k.yaml'
      - 'configs/plotting/baseline/tsne/hcl.yaml'
      # - 'configs/plotting/baseline/tsne/jax_mouse_prenatal.yaml'
      - 'configs/plotting/baseline/tsne/mca.yaml'
      - 'configs/plotting/baseline/tsne/mnist.yaml'
      - 'configs/plotting/baseline/tsne/ng20.yaml'
      - 'configs/plotting/baseline/tsne/tree.yaml'
      - 'configs/plotting/baseline/umap/act.yaml'
      # - 'configs/plotting/baseline/umap/aqc.yaml'
      - 'configs/plotting/baseline/umap/emnist.yaml'
      - 'configs/plotting/baseline/umap/epi.yaml'
      - 'configs/plotting/baseline/umap/gast10k.yaml'
      - 'configs/plotting/baseline/umap/hcl.yaml'
      - 'configs/plotting/baseline/umap/mca.yaml'
      - 'configs/plotting/baseline/umap/mnist.yaml'
      - 'configs/plotting/baseline/umap/ng20.yaml'
      - 'configs/plotting/baseline/umap/tree.yaml'

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
