"""Generate the paired learning-rate diagnostic for mechanism-ablation collapse.

Every scientific setting is copied from the completed seed-42 v2 ablation.
The two members of each pair differ only in ``model.init_args.lr`` and in
run/output identity.  Historical (detached-statistics) embedding
standardization is made explicit so this experiment does not mix the learning
rate hypothesis with the separate standardization fix.
"""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
RUN_DIR = HERE / "runs"
SWEEP_DIR = HERE / "sweep"
PROJECT = "TopoBranch_latent_ablation_lr_diagnostic"
SEED = 42
LEARNING_RATES = {"lr1e3": 1.0e-3, "lr3e4": 3.0e-4}
TARGETS = {
    "hcl": ("full", "b4_single_density"),
    "epi": (
        "full",
        "base",
        "b2_bidirectional",
        "b4_single_density",
        "b5_multi_density",
        "r1_distance",
        "r2_unidirectional",
    ),
    "mnist": ("full", "b5_multi_density"),
}


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def one_callback(callbacks: list[dict], suffix: str) -> dict:
    matches = [item for item in callbacks if item["class_path"].endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"Expected one {suffix}, found {len(matches)}")
    return matches[0]


def source_config(dataset: str, variant: str) -> Path:
    return (
        ROOT
        / "configs/encoder_bench/ablation_mechanism_latent_v2/runs"
        / f"ablation_v2_latent-bn_{dataset}_{variant}_seed42.yaml"
    )


def build(dataset: str, variant: str, lr_label: str, lr: float) -> tuple[str, dict]:
    cfg = copy.deepcopy(load(source_config(dataset, variant)))
    run_name = f"ablation_lrdiag_latent-bn_{dataset}_{variant}_{lr_label}_seed{SEED}"
    out_root = (
        f"outputs/ablation/lr_diagnostic/{dataset}/{variant}/{lr_label}/seed{SEED}"
    )

    cfg["seed_everything"] = SEED
    model_args = cfg["model"]["init_args"]
    model_args["lr"] = lr
    model_args["stable_embedding_standardization"] = False
    model_args["embedding_std_floor"] = 1.0e-4

    logger = cfg["trainer"]["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "project": PROJECT,
            "save_dir": "wandb/ablation_lr_diagnostic",
            "tags": [
                "ablation-lr-diagnostic",
                "historical-standardization",
                dataset,
                variant,
                lr_label,
                f"seed{SEED}",
            ],
        }
    )

    callbacks = cfg["trainer"]["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {"dirpath": f"{out_root}/checkpoints", "filename": f"{run_name}-{{epoch:04d}}"}
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/lr_diagnostic/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"

    method_name = f"latent-bn-{variant}-{lr_label}-lrdiag"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {"output_dir": f"{out_root}/figure", "method_name": method_name}
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")["init_args"].update(
        {
            "dataset_name": f"{dataset}_{variant}_{lr_label}_lrdiag_seed{SEED}",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": method_name,
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    SWEEP_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()
    for stale in SWEEP_DIR.glob("*.yaml"):
        stale.unlink()

    run_paths: list[Path] = []
    for dataset, variants in TARGETS.items():
        for variant in variants:
            for lr_label, lr in LEARNING_RATES.items():
                run_name, cfg = build(dataset, variant, lr_label, lr)
                path = RUN_DIR / f"{run_name}.yaml"
                header = (
                    "# Generated by ablation_lr_diagnostic/generate_configs.py\n"
                    f"# dataset={dataset}; variant={variant}; lr={lr}; seed={SEED}\n"
                    "# Only learning rate and run/output identity differ within each pair.\n"
                )
                with path.open("w", encoding="utf-8") as handle:
                    handle.write(header)
                    yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
                run_paths.append(path)

    sweep = {
        "program": "main.py",
        "method": "grid",
        "project": PROJECT,
        "name": "latent_ablation_collapse_lr1e3_vs_lr3e4_seed42_c89",
        "parameters": {
            "config": {
                "values": [path.relative_to(ROOT).as_posix() for path in run_paths]
            }
        },
        "command": ["${env}", "${interpreter}", "${program}", "fit", "${args}"],
    }
    sweep_path = SWEEP_DIR / "sweep_lr1e3_vs_lr3e4_seed42_c89.yaml"
    with sweep_path.open("w", encoding="utf-8") as handle:
        handle.write("# Paired 22-run collapse learning-rate diagnostic on c89.\n")
        yaml.safe_dump(sweep, handle, sort_keys=False, allow_unicode=True)
    print(f"Wrote {len(run_paths)} configs and {sweep_path}")


if __name__ == "__main__":
    main()
