seed_everything: 42
data:
  class_path: data_model.M1datamodel_activity.DMTBaseDataModule
  init_args:
    pca_dim: 64
    batch_size: 10299
    num_workers: 0
    K: 200
    n_f_per_cluster: 3
    n_hop: 1
    l_token: 10
    data_path: /usr/storage/ruizhe/zangzelin/data
model:
  class_path: model.baseline_tri.DMTEVT_model
  init_args:
    method: _phate
    data_name: act
    num_input_dim: 561
    n_components: 2
    p1: 2
    p2: 2
    p3: 0
    random_state: 42
trainer:
  max_epochs: 1
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  enable_checkpointing: false
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: baseline_phate_act
      project: DiffTree_rz
      save_dir: wandb
  callbacks:
  - class_path: callbacks.paper_embedding_plot_callback.VisualizationCallback
    init_args:
      output_dir: outputs/paper_embeddings/baseline/phate/act
      dataset_name: ACT
      method_name: PHATE
      every_n_epochs: 1
      max_plot_samples: 40000
      save_formats:
      - png
      scale_down_factor: 3.0
      dpi: 800
      base_point_size: 1.2
      min_point_size: 0.5
      alpha: 0.6
      edge_color: none
  - class_path: callbacks.Eval_density.FidelityEvalCallback
    init_args:
      every_n_epochs: 1
      down_sample: 3000
      knn_k: 12
      density_k: 15
