program: main.py
method: grid
project: DiffTree_rz
name: dmtme_dataset_weighted_sweep

parameters:
  config:
    values:
      - 'configs/dmtme_dataset_weighted/ACT.yaml'
      - 'configs/dmtme_dataset_weighted/EMNIST.yaml'
      - 'configs/dmtme_dataset_weighted/HCL.yaml'
      - 'configs/dmtme_dataset_weighted/MCA.yaml'
      - 'configs/dmtme_dataset_weighted/NG20.yaml'
      - 'configs/dmtme_dataset_weighted/aqc.yaml'
      - 'configs/dmtme_dataset_weighted/epi.yaml'
      - 'configs/dmtme_dataset_weighted/gast10k.yaml'
  seed_everything:
    values:
      - 42
      - 43
      - 44
      - 45

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
