seed_everything: 42

data:
  class_path: data_model.M1datamodel_celegan.DMTBaseDataModule
  init_args:
    pca_dim: 64
    batch_size: 1000
    num_workers: 1
    K: 50
    n_f_per_cluster: 3
    n_hop: 1
    l_token: 10
    data_path: /usr/storage/ruizhe/zangzelin/data
    include_time_label: true
    exclude_unannotated: true
    standardize: true

model:
  class_path: model.DiffTreeVQ_v2.DMTEVT_model
  init_args:
    num_input_dim: 2766
    # sigma: 0.05
    lr: 0.005 # 0.00002 # 0.001, 0.005, 0.01
    # w_nb: 1 # not change
    # w_fp: 1 # not change
    # weight_nepo: 0.9 # 0.1, 0.2, 0.5, 1, 2, 5
    # weight_mse: 0 # 0.1, 0.2, 0.5, 1, 2, 5
    # sample_rate_feature: 0.9
    # nu_lat: [0.02, 0.01]
    nu_lat: 0.01
    nu_emb: -1
    exaggeration_lat: 2
    exaggeration_emb: -1
    sample_rate_feature: 1.00
    # T_num_attention_heads: 48
    T_hidden_size: 512
    t_output_dim: 40
    weight_decay: 0.0000000001
    num_use_moe: 1
    T_num_layers: 3
    max_epochs: 1000
    tree_depth: 10
    step2_epoch: 1000
    step2_r_epoch: 1000
    use_tree_rout: True
    gen_data_bool: False
    ec_ce_weight: 2
    weightrout: 0.1
    loss_type: 'G'
    all_g_l_weight: 0.95
    exp_b: 0.4
    exp_min: 1e-6
    num_use_mlevel_list: [0.5, 1, 5, 10]
    # zzlfct: 0.5
    # p3: 1
    # use_orthogonal: True
    # T_intermediate_size: 300
    # T_hidden_dropout_prob: 0.0
    # T_attention_probs_dropout_prob: 0.0
    # num_muti_mask: 10
    # vis_dim: 2
    # trans_out_dim: 2048
    # n_neg_sample: 4
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: difftree_celegan
      project: C_HDTREE
      save_dir: wandb
  callbacks:
    # - class_path: callbacks.xc_plot_clustering.EvalCallBack
    #   init_args:
    #     inter: 2
    #     dirpath: 'zzl_checkpoints/'
    #     fully_eval: False
    #     dataset: 'mnist_4gpu'
    #     vis_rout: True
    #     save_results: True
    - class_path: callbacks.xc_save_model.SaveLatestSubmodulesCallback
      init_args:
        output_dir: 'zzl_checkpoints/celegan'
    - class_path: callbacks.xc_plot_callback.VisualizationCallback
      init_args:
        output_dir: 'zzl_checkpoints/celegan'
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: 'zzl_checkpoints/celegan'
        monitor: 'loss_all'
        filename: 'difftree-{epoch:02d}-{loss_all:.2f}'
        save_last: true
  max_epochs: 500
  # limit_train_batches: 10000
  devices: 1
  # precision: 64
  accelerator: gpu
  check_val_every_n_epoch: 100
  enable_checkpointing: True
