program: main.py
method: grid
project: DiffTree_rz
name: topobranch_density_ablation_no_full_12_512_0018_9dataset_5seed
parameters:
  config:
    values:
    - configs/ablation/act_no_density.yaml
    - configs/ablation/act_single_scale.yaml
    - configs/ablation/aqc_no_density.yaml
    - configs/ablation/aqc_single_scale.yaml
    - configs/ablation/emnist_no_density.yaml
    - configs/ablation/emnist_single_scale.yaml
    - configs/ablation/epi_no_density.yaml
    - configs/ablation/epi_single_scale.yaml
    - configs/ablation/gast10k_no_density.yaml
    - configs/ablation/gast10k_single_scale.yaml
    - configs/ablation/hcl_no_density.yaml
    - configs/ablation/hcl_single_scale.yaml
    - configs/ablation/mca_no_density.yaml
    - configs/ablation/mca_single_scale.yaml
    - configs/ablation/ng20_no_density.yaml
    - configs/ablation/ng20_single_scale.yaml
    - configs/ablation/tree_no_density.yaml
    - configs/ablation/tree_single_scale.yaml
  seed_everything:
    values:
    - 42
    - 43
    - 44
    - 45
    - 46
  model.init_args.density_k:
    values:
    - 12
  model.init_args.density_num_anchors:
    values:
    - 512
  model.init_args.max_epochs:
    values:
    - 1000
  trainer.max_epochs:
    values:
    - 1000
command:
- ${env}
- ${interpreter}
- ${program}
- fit
- ${args}
