program: main.py
method: grid
project: DiffTree_rz
name: density_lambda_sensitivity_multiscale_12_512_5seed

parameters:
  config:
    values:
      - configs/ablation/component/gast10k_full.yaml
      - configs/ablation/component/hcl_full.yaml
      - configs/ablation/component/mca_full.yaml
      - configs/ablation/component/ng20_full.yaml
  seed_everything:
    values: [42, 43, 44, 45, 46]
  model.init_args.density_weight:
    values: [0.0001, 0.0005, 0.001, 0.0018, 0.003, 0.006, 0.01, 0.02]
  model.init_args.density_k:
    values: [12]
  model.init_args.density_num_anchors:
    values: [512]
  model.init_args.density_scale_mode:
    values: [multi]
  model.init_args.max_epochs:
    values: [1000]
  trainer.max_epochs:
    values: [1000]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
