"""Generate E14 NG20 Transformer information-preservation experiments.

Each arm changes one axis from E11-A6, the best minimal latent-Transformer
recipe: M32/r16/d224, two LayerNorm blocks, no dropout, input BatchNorm and
mean pooling.  The shared projection head, objectives, data, callbacks,
epochs and actual batch size remain unchanged.
"""

import copy
from pathlib import Path

import yaml


HERE = Path(__file__).resolve().parent
RUNS_DIR = HERE / "runs"
SWEEP_PATH = (
    HERE.parent
    / "sweep"
    / "encoder_bench_ng20_e14_transformer_information_seed42.yaml"
)
TEMPLATE = (
    HERE.parent
    / "sweep_e11"
    / "runs"
    / "ng20_latent_m32_r16_nodrop_inputbn_lr0p001_seed42.yaml"
)
PROJECT = "TopoBranch_encoder_bench_NG20"
LR_VALUES = {"0p005": 0.005, "0p001": 0.001}

BASE = {
    "num_latents": 32,
    "d_token": 224,
    "num_layers": 2,
    "num_heads": 4,
    "ffn_ratio": 4.0,
    "dropout": 0.0,
    "attn_dropout": 0.0,
    "latent_rank": 16,
    "pooling": "mean",
    "final_norm": True,
    "block_norm": "layernorm",
    "force_mem_efficient": True,
    "input_norm": "batchnorm",
}

# slug -> (kwargs overrides, W&B label, scientific question)
ARMS = {
    "latent_m16_inputbn": (
        {"num_latents": 16},
        "latent-m16-r16-inputbn",
        "B1: reduce M32 to M16 to test over-mixing versus density resolution",
    ),
    "latent_m32_weightedmean_inputbn": (
        {"pooling": "weighted_mean"},
        "latent-m32-r16-weightedmean-inputbn",
        "B2: identity-aware channel-wise pooling initialized exactly as mean",
    ),
    "latent_m32_inputresidual_inputbn": (
        {"input_residual": True},
        "latent-m32-r16-inputresidual-inputbn",
        "B3: zero-initialized direct D-to-40 path to preserve input directions",
    ),
}


def _rewrite_outputs(cfg, name, label):
    out_root = f"outputs/encoder_tuning/E14/{name}"
    for callback in cfg["trainer"]["callbacks"]:
        init_args = callback.get("init_args", {})
        class_path = callback["class_path"]
        if class_path.endswith("ModelCheckpoint"):
            init_args["dirpath"] = f"{out_root}/checkpoints"
            init_args["filename"] = name + "-{epoch:04d}"
        elif class_path.endswith("VisualizationCallback"):
            init_args["output_dir"] = f"{out_root}/plots"
            init_args["embedding_method_name"] = label
        elif class_path.endswith("HeterogeneityPlotCallback"):
            init_args["output_dir"] = f"{out_root}/heterogeneity"
        elif class_path.endswith("RuntimeProfilerCallback"):
            init_args["output_path"] = (
                f"results/encoder_tuning/E14/{name}/runtime.csv"
            )
        elif class_path.endswith("PaperEmbeddingCallback"):
            init_args["output_dir"] = f"{out_root}/paper"
            init_args["method_name"] = label
        elif class_path.endswith("RuntimeInfoCallback"):
            init_args["output_dir"] = f"{out_root}/runtime_info"


def main():
    template = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8"))
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    written = []

    for slug, (overrides, label, purpose) in ARMS.items():
        kwargs = copy.deepcopy(BASE)
        kwargs.update(overrides)
        for lr_tag, lr in LR_VALUES.items():
            cfg = copy.deepcopy(template)
            name = f"ng20_{slug}_lr{lr_tag}_seed42"
            cfg["seed_everything"] = 42
            model_args = cfg["model"]["init_args"]
            model_args["lr"] = lr
            model_args["encoder_type"] = "latent_transformer"
            model_args["encoder_kwargs"] = copy.deepcopy(kwargs)
            logger_args = cfg["trainer"]["logger"]["init_args"]
            logger_args["name"] = f"{label}_ng20_lr{lr}_seed42"
            logger_args["project"] = PROJECT
            _rewrite_outputs(cfg, name, label)

            header = (
                "# Generated by configs/encoder_bench/sweep_e14/"
                "generate_e14_configs.py\n"
                f"# {purpose}.\n"
                f"# Learning rate: {lr}; seed: 42; actual batch 4096.\n"
                "# Projection head, objectives, data, augmentation, schedule "
                "and callbacks unchanged.\n"
            )
            path = RUNS_DIR / f"{name}.yaml"
            path.write_text(
                header
                + yaml.safe_dump(
                    cfg, sort_keys=False, default_flow_style=False
                ),
                encoding="utf-8",
            )
            written.append(
                f"configs/encoder_bench/sweep_e14/runs/{name}.yaml"
            )

    sweep = (
        "# E14: preserve discriminative information in the latent Transformer.\n"
        "program: main.py\n"
        "method: grid\n"
        f"project: {PROJECT}\n"
        "name: encoder_bench_ng20_e14_transformer_information_seed42\n"
        "command:\n"
        "  - ${env}\n"
        "  - ${interpreter}\n"
        "  - ${program}\n"
        "  - fit\n"
        "  - ${args}\n"
        "parameters:\n"
        "  config:\n"
        "    values:\n"
        + "".join(f"      - {path}\n" for path in written)
    )
    SWEEP_PATH.write_text(sweep, encoding="utf-8")
    print(f"wrote {len(written)} run configs and {SWEEP_PATH.name}")


if __name__ == "__main__":
    main()
