program: main.py
method: grid
project: DiffTree_rz
name: difftree_with_new_metrics_12_512_0018_5seed

parameters:
  config:
    values:
      - 'configs/baseline_with_new_metrics/difftree/tree.yaml'
      - 'configs/baseline_with_new_metrics/difftree/hcl.yaml'
      - 'configs/baseline_with_new_metrics/difftree/gast10k.yaml'
      - 'configs/baseline_with_new_metrics/difftree/mca.yaml'
      - 'configs/baseline_with_new_metrics/difftree/epi.yaml'
      - 'configs/baseline_with_new_metrics/difftree/emnist.yaml'
      - 'configs/baseline_with_new_metrics/difftree/ng20.yaml'
      - 'configs/baseline_with_new_metrics/difftree/act.yaml'

  seed_everything:
    values: [42, 43, 44, 45, 46]

  model.init_args.density_k:
    values: [12]

  model.init_args.density_num_anchors:
    values: [512]

  model.init_args.density_weight:
    values: [0.0018]

  model.init_args.max_epochs:
    values: [1000]

  trainer.max_epochs:
    values: [1000]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}
