program: main.py
method: grid
project: BatchEffect_HDTREE
name: sweepMnist
parameters:
  config:
    values: [
      "conf/difftree/G_xc_1gpu_mnist.yaml",
    ]
  data.n_hop:
    values: [1, 2, 3, 4, 5, 6]
  model.loss_type:
    values: ['A']
  model.all_g_l_weight:
    values: [0.95, 0.9, 0.85, 0.8, 0.75, 0.7]
  model.nu_lat:
    values: [0.01, 0.005, 0.002, ]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}

