program: main.py
method: grid
project: C_HDTREE
name: sweepMnist
parameters:
  config:
    values: [
      "conf/step1/G_xc_1gpu_celegan.yaml",
    ]
  model.loss_type:
    values: ['G']
  data.K:
    values: [50, 100, 200, 300, 500]
  model.exp_b:
    values: [0.1, 0.3, 0.5, 0.7, 0.9]
  model.num_use_mlevel_list:
    values: [[1, 2, 10, 15], [1, 2, 5, 10], [0.5, 1, 2, 5]]


command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}

