program: main.py
method: grid
project: C_HDTREE
name: sweepMnist
parameters:
  config:
    values: [
      "conf/difftree/G_xc_1gpu_marrow_Var_G.yaml",
    ]
  data.n_hop:
    values: [1,2]
  model.loss_type:
    values: ['G']
  data.K:
    values: [3,4,5,6, 10, 15, 20, 40, 60, 80]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - ${args}

