"""Generate the publication runtime sweep for the final latent Transformer.

The dataset loaders and sample-size grid come from the matched runtime sweep
used by the supplementary table. Only the final model/runtime settings are
updated here. Data subsampling always uses seed 42, while each concrete config
has an explicit training seed so run names and local CSV files stay unique.
"""

from copy import deepcopy
from pathlib import Path
import re

import yaml


ROOT = Path(__file__).resolve().parents[3]
SOURCE_DIR = ROOT / "configs" / "runtime" / "difftree"
OUTPUT_DIR = Path(__file__).resolve().parent
RUNS_DIR = OUTPUT_DIR / "runs"
SWEEP_DIR = OUTPUT_DIR / "sweep"

PROJECT = "TopoBranch_latent_runtime_150epoch"
EPOCHS = 150
TRAINING_SEEDS = (42, 43, 44)

ENCODER_KWARGS = {
    "num_latents": 32,
    "d_token": 224,
    "num_layers": 2,
    "num_heads": 4,
    "ffn_ratio": 4.0,
    "dropout": 0.0,
    "attn_dropout": 0.0,
    "latent_rank": 16,
    "pooling": "mean",
    "final_norm": True,
    "input_norm": "batchnorm",
    "force_mem_efficient": True,
}

SOURCE_PATTERN = re.compile(r"^difftree_(?P<dataset>.+)_n(?P<size>\d+)\.yaml$")


def source_configs():
    parsed = []
    for path in SOURCE_DIR.glob("difftree_*_n*.yaml"):
        match = SOURCE_PATTERN.match(path.name)
        if match is None:
            continue
        parsed.append((match.group("dataset"), int(match.group("size")), path))
    return sorted(parsed, key=lambda item: (item[0], item[1]))


def build_config(base, dataset, size, training_seed):
    config = deepcopy(base)
    config["seed_everything"] = training_seed

    data_args = config["data"]["init_args"]
    data_args["seed"] = 42
    data_args["sample_data_size"] = size

    model_args = config["model"]["init_args"]
    model_args.update(
        {
            "num_train_data": size,
            "lr": 0.001,
            "max_epochs": EPOCHS,
            "nu_lat": 0.01,
            "density_weight": 0.0018,
            "density_k": 12,
            "density_num_anchors": 512,
            "encoder_type": "latent_transformer",
            "encoder_kwargs": deepcopy(ENCODER_KWARGS),
        }
    )

    run_name = f"runtime_latent_{dataset}_n{size}_seed{training_seed}"
    artifact_root = f"outputs/runtime/latent_transformer_150epoch/{run_name}"
    result_root = f"results/runtime/latent_transformer_150epoch/{run_name}"

    trainer = config["trainer"]
    trainer.update(
        {
            "max_epochs": EPOCHS,
            "accelerator": "gpu",
            "devices": 1,
            "precision": "16-mixed",
            "benchmark": True,
            "enable_checkpointing": False,
            "limit_val_batches": 0,
            "num_sanity_val_steps": 0,
            "log_every_n_steps": 500,
            "logger": {
                "class_path": "lightning.pytorch.loggers.WandbLogger",
                "init_args": {
                    "name": run_name,
                    "project": PROJECT,
                    "group": f"runtime_{dataset}",
                    "tags": [
                        "runtime",
                        "latent-transformer",
                        "150-epoch",
                        dataset,
                        f"n{size}",
                        f"seed{training_seed}",
                    ],
                    "save_dir": "wandb/runtime_latent_150epoch",
                    "log_model": False,
                },
            },
            "callbacks": [
                {
                    "class_path": "callbacks.runtime_profiler.RuntimeProfilerCallback",
                    "init_args": {"output_path": f"{result_root}/runtime.csv"},
                },
                {
                    "class_path": "callbacks.runtime_info_callback.RuntimeInfoCallback",
                    "init_args": {"output_dir": f"{artifact_root}/runtime_info"},
                },
            ],
        }
    )
    # This key is retained by some old runtime configs; keeping it above the
    # run length ensures validation is also disabled on older Lightning.
    trainer["check_val_every_n_epoch"] = 1000
    return config, run_name


def main():
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    SWEEP_DIR.mkdir(parents=True, exist_ok=True)

    generated = []
    sources = source_configs()
    if len(sources) != 27:
        raise RuntimeError(f"Expected 27 matched runtime configs, found {len(sources)}")

    for dataset, size, source_path in sources:
        with source_path.open("r", encoding="utf-8") as handle:
            base = yaml.safe_load(handle)
        for training_seed in TRAINING_SEEDS:
            config, run_name = build_config(base, dataset, size, training_seed)
            output_path = RUNS_DIR / f"{run_name}.yaml"
            header = (
                "# Generated by configs/runtime/latent_transformer_150epoch/"
                "generate_configs.py\n"
                f"# Dataset={dataset}, N={size}, training_seed={training_seed}, "
                "data_seed=42, epochs=150.\n"
            )
            with output_path.open("w", encoding="utf-8", newline="\n") as handle:
                handle.write(header)
                yaml.safe_dump(config, handle, sort_keys=False)
            generated.append(output_path)

    sweep = {
        "program": "main.py",
        "method": "grid",
        "project": PROJECT,
        "name": "latent_transformer_runtime_150epoch_3seed",
        "parameters": {
            "config": {
                "values": [path.relative_to(ROOT).as_posix() for path in generated]
            }
        },
        "command": [
            "${env}",
            "${interpreter}",
            "${program}",
            "fit",
            "${args}",
        ],
    }
    sweep_path = SWEEP_DIR / "sweep_latent_runtime_150epoch_3seed.yaml"
    with sweep_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# 27 dataset-size settings x seeds 42/43/44 = 81 runs.\n")
        yaml.safe_dump(sweep, handle, sort_keys=False)

    print(f"Generated {len(generated)} run configs and {sweep_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
