"""Generate the numerically stabilized rerun of the latent mechanism ablation."""

from __future__ import annotations

import copy
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
RUN_DIR = HERE / "runs"
SWEEP_DIR = HERE / "sweep"
SEED = 42
DATASETS = ("hcl", "epi", "mnist")
VARIANTS = (
    "full",
    "r1_distance",
    "r2_unidirectional",
    "r3_allpair",
    "r4_single_density",
    "r5_no_density",
    "base",
    "b1_rank",
    "b2_bidirectional",
    "b3_hardpair",
    "b4_single_density",
    "b5_multi_density",
)


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def one_callback(callbacks: list[dict], suffix: str) -> dict:
    matches = [item for item in callbacks if item["class_path"].endswith(suffix)]
    if len(matches) != 1:
        raise ValueError(f"Expected one {suffix}, found {len(matches)}")
    return matches[0]


def build(dataset: str, variant: str) -> tuple[str, dict]:
    source = ROOT / (
        "configs/encoder_bench/ablation_mechanism_latent/runs/"
        f"ablation_latent-bn_{dataset}_{variant}_seed{SEED}.yaml"
    )
    cfg = copy.deepcopy(load(source))
    run_name = f"ablation_v2_latent-bn_{dataset}_{variant}_seed{SEED}"
    out_root = (
        f"outputs/ablation/latent_mechanism_v2/{dataset}/{variant}/seed{SEED}"
    )

    logger = cfg["trainer"]["logger"]["init_args"]
    logger.update(
        {
            "name": run_name,
            "project": "TopoBranch_latent_mechanism_ablation_v2",
            "save_dir": "wandb/latent_mechanism_ablation_v2",
            "tags": ["numerical-stability-v2", dataset, variant, f"seed{SEED}"],
        }
    )

    callbacks = cfg["trainer"]["callbacks"]
    one_callback(callbacks, "ModelCheckpoint")["init_args"].update(
        {
            "dirpath": f"{out_root}/checkpoints",
            "filename": f"{run_name}-{{epoch:04d}}",
        }
    )
    one_callback(callbacks, "xc_plot_callback.VisualizationCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/diagnostics"
    one_callback(callbacks, "HeterogeneityPlotCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/heterogeneity"
    one_callback(callbacks, "RuntimeProfilerCallback")["init_args"][
        "output_path"
    ] = f"results/ablation/latent_mechanism_v2/{run_name}/runtime.csv"
    one_callback(callbacks, "RuntimeInfoCallback")["init_args"][
        "output_dir"
    ] = f"{out_root}/runtime_info"
    one_callback(callbacks, "PaperEmbeddingCallback")["init_args"].update(
        {
            "output_dir": f"{out_root}/figure",
            "method_name": f"latent-bn-{variant}-v2",
        }
    )
    one_callback(callbacks, "SaveConsolidatedEmbeddingsCallback")["init_args"].update(
        {
            "dataset_name": f"{dataset}_{variant}_v2_seed{SEED}",
            "output_dir": f"{out_root}/final_embedding",
            "embedding_method_name": f"latent-bn-{variant}-v2",
        }
    )
    return run_name, cfg


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    SWEEP_DIR.mkdir(parents=True, exist_ok=True)
    for stale in RUN_DIR.glob("*.yaml"):
        stale.unlink()

    run_paths: list[str] = []
    for dataset in DATASETS:
        for variant in VARIANTS:
            run_name, cfg = build(dataset, variant)
            path = RUN_DIR / f"{run_name}.yaml"
            header = (
                "# Generated by configs/encoder_bench/ablation_mechanism_latent_v2/"
                "generate_configs.py\n"
                f"# Stabilized rerun: {dataset}, {variant}, seed {SEED}.\n"
                "# Scientific settings exactly match v1; only run/output identity differs.\n"
            )
            with path.open("w", encoding="utf-8") as handle:
                handle.write(header)
                yaml.safe_dump(cfg, handle, sort_keys=False, allow_unicode=True)
            run_paths.append(path.relative_to(ROOT).as_posix())

    sweep = {
        "program": "main.py",
        "method": "grid",
        "project": "TopoBranch_latent_mechanism_ablation_v2",
        "name": "latent_bn_old_mechanism_stable_v2_mnist_hcl_epi_seed42",
        "parameters": {"config": {"values": run_paths}},
        "command": ["${env}", "${interpreter}", "${program}", "fit", "${args}"],
    }
    path = SWEEP_DIR / "sweep_seed42.yaml"
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Stabilized full rerun: 3 datasets x 12 variants x seed 42.\n")
        yaml.safe_dump(sweep, handle, sort_keys=False, allow_unicode=True)
    print(f"Wrote {len(run_paths)} configs and {path}")


if __name__ == "__main__":
    main()
