"""Generates HCL latent-bn seed 43/44 configs.

Every HCL Transformer conclusion currently rests on seed 42 alone - including
the null verdicts of E15 and the claim that the latent encoder beats the MLP on
SVC, kNN preservation and trustworthiness. Two runs at the selected learning
rate (1e-3, S=0.8532 at seed 42) turn that into a three-seed result.

Run:
    python configs/encoder_bench/sweep_e16/generate_e16_configs.py
"""

import copy
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
RUNS_DIR = HERE / "runs"
# (template, slug, wandb-name prefix) -> seeds 43/44 each.
# latent-bn is the E13 recipe; latent-rank32 is the E15 T3 arm whose lr-1e-3 run
# crashed on a wandb.init timeout and, once rerun, turned out to be the strongest
# Transformer result on HCL rather than the null the incomplete data suggested.
TARGETS = [
    (
        HERE.parent / "sweep_e13" / "runs" / "hcl_latent_bn_lr0p001_seed42.yaml",
        "hcl_latent_bn_lr0p001",
        "latent-bn_hcl_lr0.001",
    ),
    (
        HERE.parent / "sweep_e15" / "runs" / "hcl_latent_rank32_lr0p001_seed42.yaml",
        "hcl_latent_rank32_lr0p001",
        "latent-rank32_hcl_lr0.001",
    ),
]
SEEDS = [43, 44]


def main():
    RUNS_DIR.mkdir(parents=True, exist_ok=True)

    for template_path, slug, wandb_prefix in TARGETS:
      template = yaml.safe_load(template_path.read_text(encoding="utf-8"))
      for seed in SEEDS:
        cfg = copy.deepcopy(template)
        name = f"{slug}_seed{seed}"
        out_root = f"outputs/encoder_tuning/E16/{name}"

        cfg["seed_everything"] = seed
        cfg["trainer"]["logger"]["init_args"]["name"] = f"{wandb_prefix}_seed{seed}"

        for callback in cfg["trainer"]["callbacks"]:
            init_args = callback.setdefault("init_args", {})
            path = callback["class_path"]
            if path.endswith("ModelCheckpoint"):
                init_args["dirpath"] = f"{out_root}/checkpoints"
                init_args["filename"] = name + "-{epoch:04d}"
            elif path.endswith("VisualizationCallback"):
                init_args["output_dir"] = f"{out_root}/plots"
            elif path.endswith("HeterogeneityPlotCallback"):
                init_args["output_dir"] = f"{out_root}/heterogeneity"
            elif path.endswith("RuntimeProfilerCallback"):
                init_args["output_path"] = (
                    f"results/encoder_tuning/E16/{name}/runtime.csv"
                )
            elif path.endswith("PaperEmbeddingCallback"):
                init_args["output_dir"] = f"{out_root}/paper"
            elif path.endswith("RuntimeInfoCallback"):
                init_args["output_dir"] = f"{out_root}/runtime_info"

        header = (
            "# Generated by configs/encoder_bench/sweep_e16/generate_e16_configs.py\n"
            f"# HCL latent-bn seed confirmation, seed {seed}, lr 1e-3.\n"
            "# Identical to the E13 seed-42 run except for the seed and artifact paths.\n"
        )
        path = RUNS_DIR / f"{name}.yaml"
        path.write_text(
            header + yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False),
            encoding="utf-8",
        )
        print(f"wrote {name}.yaml")


if __name__ == "__main__":
    main()
