program: main.py
method: grid
project: DiffTree_rz
name: topobranch_density_ablation_no_full_12_512_0018_9dataset_5seed
parameters:
  config:
    values:
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/act_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/act_single_scale.yaml
    - configs/ablation/component/aqc_no_density.yaml
    - configs/ablation/component/aqc_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/emnist_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/emnist_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/epi_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/epi_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/gast10k_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/gast10k_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/hcl_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/hcl_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/mca_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/mca_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/ng20_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/ng20_single_scale.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/tree_no_density.yaml
    # completed: valid seeds 42,43,44,45,46
    # - configs/ablation/component/tree_single_scale.yaml
  seed_everything:
    values:
    - 42
    - 43
    - 44
    - 45
    - 46
  model.init_args.density_k:
    values:
    - 12
  model.init_args.density_num_anchors:
    values:
    - 512
  model.init_args.max_epochs:
    values:
    - 1000
  trainer.max_epochs:
    values:
    - 1000
command:
- ${env}
- ${interpreter}
- ${program}
- fit
- ${args}
